window.NOC=window.NOC||{};
NOC.Herramientas=(()=>{
 const TABLES={
 clientes:{label:"Clientes",columns:["id","nombre","apellidos","nombre_tienda","telefono","email","dni_cif","direccion_facturacion","cp_facturacion","localidad_facturacion","provincia_facturacion","direccion_entrega","cp_entrega","localidad_entrega","provincia_entrega","comercial","observaciones","tipo_fiscal","envio_habitual_id","created_at"],template:["nombre","apellidos","nombre_tienda","telefono","email","dni_cif","direccion_facturacion","cp_facturacion","localidad_facturacion","provincia_facturacion","direccion_entrega","cp_entrega","localidad_entrega","provincia_entrega","comercial","observaciones","tipo_fiscal","envio_habitual_id"],required:["nombre_tienda"],match:["dni_cif","nombre_tienda"]},
 articulos:{label:"Artículos",columns:["id","nombre_producto","sku","precio_venta","precio_coste","tipo_articulo","tipo_prenda","estilo","fabrica","anio","mes","created_at"],template:["nombre_producto","sku","precio_venta","precio_coste","tipo_articulo","tipo_prenda","estilo","fabrica","anio","mes"],required:["nombre_producto"],numeric:["precio_venta","precio_coste","anio"],match:["sku","nombre_producto"]},
 tipos_envio:{label:"Tipos de envío",columns:["id","nombre","empresa","precio","iva_porcentaje","orden","activo","predeterminado","created_at"],template:["nombre","empresa","precio","iva_porcentaje","orden","activo","predeterminado"],required:["nombre"],numeric:["precio","iva_porcentaje","orden"],boolean:["activo","predeterminado"],match:["nombre"]},
 proformas:{label:"Proformas",columns:["id","numero","fecha","cliente_id","estado","forma_pago","envio_id","envio_precio","envio_descuento","base_imponible","iva","recargo","total","observaciones","created_at"],template:["numero","fecha","cliente_id","estado","forma_pago","envio_id","envio_precio","envio_descuento","base_imponible","iva","recargo","total","observaciones"],required:["numero","fecha","cliente_id"],numeric:["envio_precio","envio_descuento","base_imponible","iva","recargo","total"],match:["numero"]},
 lineas_proforma:{label:"Líneas de proforma",columns:["id","proforma_id","articulo_id","descripcion","precio_unitario","cantidad","descuento","tallaje","orden","es_envio"],template:["proforma_id","articulo_id","descripcion","precio_unitario","cantidad","descuento","tallaje","orden","es_envio"],required:["proforma_id","descripcion"],numeric:["precio_unitario","cantidad","descuento","orden"],boolean:["es_envio"],match:["id"]},
 facturas:{label:"Facturas",columns:["id","numero","fecha","cliente_id","proforma_id","forma_pago","base_imponible","iva","recargo","total","observaciones","created_at"],template:["numero","fecha","cliente_id","proforma_id","forma_pago","base_imponible","iva","recargo","total","observaciones"],required:["numero","fecha","cliente_id"],numeric:["base_imponible","iva","recargo","total"],match:["numero"]},
 lineas_factura:{label:"Líneas de factura",columns:["id","factura_id","articulo_id","descripcion","precio_unitario","cantidad","descuento","tallaje","orden","es_envio"],template:["factura_id","articulo_id","descripcion","precio_unitario","cantidad","descuento","tallaje","orden","es_envio"],required:["factura_id","descripcion"],numeric:["precio_unitario","cantidad","descuento","orden"],boolean:["es_envio"],match:["id"]},
 gastos:{label:"Gastos",columns:["id","fecha","empresa","tipo_gasto","cantidad","numero_factura","observaciones","created_at"],template:["fecha","empresa","tipo_gasto","cantidad","numero_factura","observaciones"],required:["fecha","empresa"],numeric:["cantidad"],match:["id"]}
 };
 const DEL=["lineas_factura","facturas","lineas_proforma","proformas","gastos","clientes","articulos","tipos_envio"],INS=["tipos_envio","clientes","articulos","proformas","lineas_proforma","facturas","lineas_factura","gastos"];
 async function render(){document.getElementById("viewContainer").innerHTML=`<div class="grid"><div class="card col-12"><h2>Importar / Exportar CSV</h2><p class="muted">CSV UTF-8 con separador ;. La importación también admite coma.</p><div class="table-wrap"><table><thead><tr><th>Tabla</th><th>Registros</th><th>Plantilla</th><th>Exportar</th><th>Importar</th></tr></thead><tbody>${Object.entries(TABLES).map(([k,m])=>`<tr><td><strong>${m.label}</strong><br><span class="muted">${k}</span></td><td id="count_${k}">—</td><td><button class="btn btn-small" onclick="NOC.Herramientas.downloadTemplate('${k}')">Plantilla</button></td><td><button class="btn btn-small" onclick="NOC.Herramientas.exportTable('${k}')">Exportar CSV</button></td><td><button class="btn btn-small btn-primary" onclick="NOC.Herramientas.chooseImport('${k}')">Importar CSV</button></td></tr>`).join("")}</tbody></table></div></div><div class="card col-6"><h2>Backup completo</h2><p class="muted">Copia adicional de seguridad de toda la base.</p><button class="btn btn-primary" onclick="NOC.Herramientas.backupAll()">Descargar backup JSON</button></div><div class="card col-6"><h2>Restaurar backup</h2><p class="muted">Sustituye los datos actuales por los del backup.</p><button class="btn btn-danger" onclick="NOC.Herramientas.chooseRestore()">Restaurar JSON</button></div><div class="card col-12"><p class="muted">Para tus datos de Excel actuales, empieza por Clientes y Artículos. Las proformas y facturas importadas requieren IDs relacionados existentes.</p></div></div><input id="csvInput" type="file" accept=".csv,text/csv" hidden><input id="jsonInput" type="file" accept=".json" hidden>`;await counts()}
 async function counts(){await Promise.all(Object.keys(TABLES).map(async t=>{const {count,error}=await NOC.API.db().from(t).select("*",{count:"exact",head:true});const e=document.getElementById("count_"+t);if(e)e.textContent=error?"Error":count??0}))}
 function downloadTemplate(t){const m=TABLES[t];downloadCsv(`${t}_plantilla.csv`,m.template,[sample(t,m.template)])}
 async function exportTable(t){const rows=await fetchAll(t),m=TABLES[t];downloadCsv(`${t}_${stamp()}.csv`,m.columns,rows);NOC.App.toast(`${rows.length} registros exportados.`)}
 function chooseImport(t){const i=document.getElementById("csvInput");i.value="";i.onchange=()=>i.files?.[0]&&previewImport(t,i.files[0]);i.click()}
 async function previewImport(t,file){try{const p=parseCsv(await file.text()),m=TABLES[t],missing=m.required.filter(x=>!p.headers.includes(x)),unknown=p.headers.filter(x=>!m.columns.includes(x)),norm=p.rows.map(r=>normalize(t,r)),errs=[];if(missing.length)errs.push("Faltan columnas obligatorias: "+missing.join(", "));if(unknown.length)errs.push("Se ignorarán: "+unknown.join(", "));norm.forEach((x,i)=>x.errors.forEach(e=>errs.push(`Fila ${i+2}: ${e}`)));window._importJob={table:t,rows:norm.map(x=>x.row)};NOC.App.modal(`<div class="modal-head"><strong>Importar ${m.label}</strong><button class="icon-btn" onclick="NOC.App.closeModal()">×</button></div><div class="modal-body"><p><strong>Archivo:</strong> ${NOC.App.esc(file.name)}</p><p><strong>Filas:</strong> ${norm.length}</p>${errs.length?`<div class="card" style="box-shadow:none"><strong>Avisos</strong><ul>${errs.slice(0,10).map(e=>`<li>${NOC.App.esc(e)}</li>`).join("")}</ul></div>`:""}<div class="field"><label>Modo</label><select id="impMode"><option value="add">Añadir</option><option value="update" selected>Actualizar / añadir</option></select></div></div><div class="modal-foot"><button class="btn" onclick="NOC.App.closeModal()">Cancelar</button><button class="btn btn-primary" ${missing.length?"disabled":""} onclick="NOC.Herramientas.runImport()">Importar</button></div>`)}catch(e){NOC.App.toast("CSV no válido: "+e.message)}}
 async function runImport(){const j=window._importJob;if(!j)return;const mode=document.getElementById("impMode").value,m=TABLES[j.table];NOC.App.closeModal();let a=0,u=0,s=0,f=0;for(const r of j.rows){try{const ex=await findExisting(j.table,r,m.match||["id"]);if(ex&&mode==="add"){s++;continue}if(ex){const p={...r};delete p.id;delete p.created_at;const {error}=await NOC.API.db().from(j.table).update(p).eq("id",ex.id);if(error)throw error;u++}else{const p=clean(r);const {error}=await NOC.API.db().from(j.table).insert(p);if(error)throw error;a++}}catch(e){console.error(e);f++}}try{await NOC.API.rpc("sincronizar_numeraciones")}catch{}NOC.App.toast(`${a} añadidos · ${u} actualizados · ${s} omitidos · ${f} errores`);render()}
 async function findExisting(t,r,keys){for(const k of keys){const v=r[k];if(v===undefined||v===null||String(v).trim()==="")continue;const {data,error}=await NOC.API.db().from(t).select("id").eq(k,v).limit(1);if(error)throw error;if(data?.length)return data[0]}return null}
 async function backupAll(){const out={format:"gestion-noc-backup",version:3,created_at:new Date().toISOString(),tables:{}};for(const t of INS)out.tables[t]=await fetchAll(t);blob(`gestion_noc_backup_${stamp()}.json`,JSON.stringify(out,null,2),"application/json");NOC.App.toast("Backup descargado.")}
 function chooseRestore(){const i=document.getElementById("jsonInput");i.value="";i.onchange=()=>i.files?.[0]&&previewRestore(i.files[0]);i.click()}
 async function previewRestore(file){try{const b=JSON.parse(await file.text());if(b.format!=="gestion-noc-backup")throw new Error("Formato incorrecto");window._restore=b;NOC.App.modal(`<div class="modal-head"><strong>Restaurar backup</strong><button class="icon-btn" onclick="NOC.App.closeModal()">×</button></div><div class="modal-body"><p>Esta operación sustituirá todos los datos actuales.</p><div class="field"><label>Escribe RESTAURAR</label><input id="restoreWord"></div></div><div class="modal-foot"><button class="btn btn-danger" onclick="NOC.Herramientas.restoreAll()">Restaurar</button></div>`)}catch(e){NOC.App.toast("Backup no válido")}}
 async function restoreAll(){if(document.getElementById("restoreWord").value!=="RESTAURAR")return NOC.App.toast("Escribe RESTAURAR");const b=window._restore;NOC.App.closeModal();for(const t of DEL){const {error}=await NOC.API.db().from(t).delete().neq("id","00000000-0000-0000-0000-000000000000");if(error)throw error}for(const t of INS){const rows=b.tables[t]||[];for(let x=0;x<rows.length;x+=250){const {error}=await NOC.API.db().from(t).insert(rows.slice(x,x+250));if(error)throw error}}try{await NOC.API.rpc("sincronizar_numeraciones")}catch{}NOC.App.toast("Backup restaurado.");render()}
 async function fetchAll(t){const o=[];let from=0;while(true){const {data,error}=await NOC.API.db().from(t).select("*").range(from,from+999);if(error)throw error;o.push(...(data||[]));if(!data||data.length<1000)break;from+=1000}return o}
 function clean(r){const p={...r};Object.keys(p).forEach(k=>{if(p[k]===""||p[k]===undefined)p[k]=null});if(!p.id)delete p.id;if(!p.created_at)delete p.created_at;return p}
 function normalize(t,r){const m=TABLES[t],o={},errors=[];Object.entries(r).forEach(([k,v0])=>{if(!m.columns.includes(k))return;let v=String(v0??"").trim();if(v===""){o[k]=null;return}if(m.numeric?.includes(k)){const n=parseNum(v);Number.isNaN(n)?errors.push(`${k} no numérico`):o[k]=n}else if(m.boolean?.includes(k))o[k]=["true","1","si","sí","yes"].includes(v.toLowerCase());else o[k]=v});m.required.forEach(k=>{if(o[k]===undefined||o[k]===null||String(o[k]).trim()==="")errors.push(`${k} obligatorio`)});return{row:o,errors}}
 function parseNum(v){let s=String(v).replace(/\s|€/g,"");if(s.includes(",")&&s.includes(".")){if(s.lastIndexOf(",")>s.lastIndexOf("."))s=s.replace(/\./g,"").replace(",",".");else s=s.replace(/,/g,"")}else if(s.includes(","))s=s.replace(",",".");return Number(s)}
 function parseCsv(text){
   text=String(text||"").replace(/^\uFEFF/,"");
   const first=(text.split(/\r?\n/,1)[0]||"");
   const semi=(first.match(/;/g)||[]).length;
   const comma=(first.match(/,/g)||[]).length;
   const d=semi>=comma?";":",";
   const rec=[];let row=[],field="",q=false;
   for(let i=0;i<text.length;i++){
     const c=text[i];
     if(q){
       if(c==='"'&&text[i+1]==='"'){field+='"';i++;}
       else if(c==='"')q=false;
       else field+=c;
     }else{
       if(c==='"')q=true;
       else if(c===d){row.push(field);field="";}
       else if(c==='\n'){row.push(field);rec.push(row);row=[];field="";}
       else if(c!=='\r')field+=c;
     }
   }
   row.push(field);
   if(row.some(x=>x!==""))rec.push(row);
   if(!rec.length)return{headers:[],rows:[]};
   const headers=rec.shift().map(x=>x.trim());
   const rows=rec.filter(r=>r.some(x=>String(x).trim()!==""))
     .map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??""])));
   return{headers,rows};
 }
 function downloadCsv(n,cols,rows){const lines=[cols.map(cell).join(";"),...rows.map(r=>cols.map(c=>cell(r[c])).join(";"))];blob(n,"﻿"+lines.join("\r\n"),"text/csv;charset=utf-8")}
 function cell(v){const s=String(v??"");return /[;"\r\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
 function blob(n,d,t){const b=new Blob([d],{type:t}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
 function stamp(){return new Date().toISOString().slice(0,10).replaceAll("-","")}
 function sample(t,cols){const s={clientes:{nombre:"Ana",apellidos:"García",nombre_tienda:"TIENDA EJEMPLO",telefono:"600000000",email:"tienda@ejemplo.com",dni_cif:"B12345678",direccion_facturacion:"Calle Ejemplo 1",cp_facturacion:"28001",localidad_facturacion:"Madrid",provincia_facturacion:"Madrid",direccion_entrega:"Calle Ejemplo 1",cp_entrega:"28001",localidad_entrega:"Madrid",provincia_entrega:"Madrid",comercial:"",observaciones:"",tipo_fiscal:"SL",envio_habitual_id:""},articulos:{nombre_producto:"CAMISETA GOLD",sku:"GOLD-001",precio_venta:"45.00",precio_coste:"18.00",tipo_articulo:"Moda",tipo_prenda:"Camiseta",estilo:"Gold",fabrica:"Fábrica ejemplo",anio:"2026",mes:"08"},tipos_envio:{nombre:"Envío Península",empresa:"GLS",precio:"6.95",iva_porcentaje:"21",orden:"10",activo:"true",predeterminado:"true"},gastos:{fecha:"2026-08-07",empresa:"Proveedor ejemplo",tipo_gasto:"Transporte",cantidad:"25.00",numero_factura:"FRA-001",observaciones:""}}[t]||{};return Object.fromEntries(cols.map(c=>[c,s[c]??""]))}
 return{render,downloadTemplate,exportTable,chooseImport,runImport,backupAll,chooseRestore,restoreAll}
})();